{% set name = "batchcrop" %}
{% set version = "0.1.1" %}
{% set sha256 = "a1f643ede3b39f306b6a79c59c30c0b2afec114769cd5c7403e464b76db85c61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/batchcrop/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py<33]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - batchcrop = batchcrop.cli.batchcrop:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - docopt
  run:
    - python
    - docopt
    - imagemagick

test:
  imports:
    - batchcrop
  commands:
    - batchcrop --help

about:
  home: https://github.com/tdegeus/batchcrop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Crop a batch of images with the same margins.'
  description: 'Crop a batch of images with the same margins.'
  doc_url: https://github.com/tdegeus/batchcrop
  dev_url: https://github.com/tdegeus/batchcrop

extra:
  recipe-maintainers:
    - tdegeus
