build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
travis:
  secure:
    BINSTAR_TOKEN: M+ppw820GCIDsObKGiJHuowelxpIO0tHk54AlJpMliz3IAMTLUBLatnOyfp7vEz0aC3VSFdbZj7+5FErcNpSHg0NIS/i0PpQUzhphjSrRTmL8TtRcoEXCLTN8/xyTDgkfnh4VWRTio4lHrp9rWfK5sA48i6QbZCNp74lyCV88KeA2pAjaRhtaZflRfIqOt+T/iUlB/n8Rl0Q4bm84vKfJAr1T/P1ycqbUIrOSnDelxhqvBzPEFfevFzakvbDcRLP3h1ULNI6+DNAbcGxO96N1DEsIj+tmyT3QgW3ilfl+zO5YN4l/spVT7ffz9jG/tn7Et/jOjYaUSDoKuLsHockLswnzCCgzqMiAMPL37zfrkQLnnp1JMoh9/pJIrNsrhWQkUjy9mxKQY7IgPgsehSB6jXd26sMun4ycvrWRaroaZGig+8YAbf0BLe3Lqbrod608TFcNx8f5UZ6Ytje4SGY6JNLCm8QBqqLkfZFKvjsND9AAlGD5kjHF5LooNQgep04uxAHQ4MH1NPpHHPmiB21x3UhQsjbYnYZuPe8SfKgep54vmsUxFfy8vSYvJnx3+vYpElsqJZSKiSxZu36hfdA5CbSBPaVP3uwaBvLnA/b02STMbtZ+31P0SN5FFaGTCaKfYmuHShL/bEX6I6le8+RbeP0YZDKdrmObu1z/9o+VOI=
